name: flutter_bnb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.0
  google_maps_flutter: ^2.6.1
  google_maps_polyline: ^1.0.3
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
